package by.trjava.coffeemachine.controller.command;

public enum CommandName {
    NOSUCHCOMMAND,
    GOTOMAKEORDERCOMMAND,
    SHOWALLDRINKS,
    AUTHORIZATION,
    UPDATEPASSWORD,
    CREATEACCOUNT,
    INCREASEBALANCE,
    GOTOSHOWALLDRINKSPAGECOMMAND,
    ADDITIONALINGREDIENT,
    GETDRINK,
    MAKEORDER,
    DELETEORDER,
    REGISTRATION,
    GOTOLOGINPAGE,
    CHANGELOCALE,
    GOTOREGISTRATIONPAGE,
    SHOWNEXTPAGE,
    SHOWPREVIOUSPAGE,
    LOGOUTCOMMAND,
    LOGOUT,
    PERSONALCABINET,
    GOTOPAGEINCREASEBALANCE,
    ORDERJOURNAL,
    GOTOINDEXPAGE
}
